version: '3'
services:
  app:
    container_name: youtube-data-process
    image: 'ferreiragui/youtube-data-process-app:1.0.0'
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ytprocessor
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ytprocessor